name: holtow

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  holtow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: digitally insured, virtually secured
        run: |   
          mkdir -p ./Season10
          wget -O ./Season10/S10_worldtour.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10worldtour/crossplay
          wget -O ./Season10/S10_crossplay.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10/crossplay
          wget -O ./Season10/S10_sponsor.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10sponsor/crossplay
          wget -O ./Season10/S10_powershift.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10powershift/crossplay
          wget -O ./Season10/S10_tdm.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10teamdeathmatch/crossplay
          wget -O ./Season10/S10_quickcash.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10quickcash/crossplay
          wget -O ./Season10/S10_pointbreak.json https://api.the-finals-leaderboard.com/v1/leaderboard/s10pointbreak/crossplay

          mkdir -p ./Season11
          wget -O ./Season11/S11_worldtour.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11worldtour/crossplay
          wget -O ./Season11/S11_crossplay.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11/crossplay
          wget -O ./Season11/S11_sponsor.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11sponsor/crossplay
          wget -O ./Season11/S11_powershift.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11powershift/crossplay
          wget -O ./Season11/S11_tdm.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11teamdeathmatch/crossplay
          wget -O ./Season11/S11_quickcash.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11quickcash/crossplay
          wget -O ./Season11/S11_pointbreak.json https://api.the-finals-leaderboard.com/v1/leaderboard/s11pointbreak/crossplay
          
      - name: commit changes
        run: |
          git config user.name "Github Action"
          git config user.email github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "[CI] updated leaderboards"
          git push
